### ISSUE TITLE
The Toblerone picture needs to be updated

### ISSUE THREAD

**Issue by vickiwang2020** [bnjbvr/rouille#67] opened 2024-06-17 15:57 UTC
New Toblerone package has been deployed since last year : https://www.bbc.com/news/business-64854720

**Comment by bnjbvr** [comment] 2024-06-17 17:33
What Toblerone picture?

Lun 17 juin 2024, à 17:58, vickiwang2020 a écrit :

**Comment by vickiwang2020** [comment] 2024-06-20 19:26
Toblerone chocolate picture of the SwissGerman Rust, lol, because this package has become the legacy, not available on market anymore. https://github.com/Georg-code/roeschti?tab=readme-ov-file#rust-uf-schwizerd%C3%BCtsch

**Comment by bnjbvr** [comment] 2024-06-21 13:35
Ah yeah, so this applies to this other repository. Closing as duplicate of https://github.com/Georg-code/roeschti/issues/8. Thanks for being on the radar of issues like this one 😁

**Closed as not planned by bnjbvr** 2024-06-21 13:35 UTC
